version: 2.1
jobs:
  buildandtest_linux_latest:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - run: sudo apt install python3.8-venv
      - checkout
      - run: make test
workflows:
  main:
    jobs:
      - buildandtest_linux_latest
